title: MobiDev Meetup
description: | # this means to ignore newlines until "baseurl:"
  Мабуть, перший україномовний ІТ мітап у східній Україні!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://meetup.mobidev.com.ua"
mobidev_ua_url: "http://mobidev.com.ua"
home_page_event_id: 2

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

future: true

collections:
  events:
    output: true

defaults:
  - scope:
      type: events
    values:
      layout: "event"
